apiVersion: v1
kind: Secret
metadata:
  name: slack-oauth-token
  namespace: tekton-watcher
type: opaque
data:
  ## This isn't an actual secret. It merely illustrates how the secret should be
  ## declared.
  ## To use the notifications feature, you must provide a Slack oauth token with
  ## the following scopes: chat:write, chat:write.public, users:read and
  ## users:read.email.
  oauth-token: dG9rZW4=
