apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-watcher
  namespace: tekton-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-watcher
  template:
    metadata:
     labels:
       app: tekton-watcher
    spec:
      serviceAccountName: tekton-watcher
      containers:
        - name: tekton-watcher
          image: alangh/tekton-watcher@sha256:64436a918df255d31b9c3d4a2be16128c812c680fcfa9d645681a772581e70c3
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - name: github-statuses-updater
              mountPath: "/etc/github-statuses-updater"
              readOnly: true
            - name: config
              mountPath: "/etc/tekton-watcher"
              readOnly: true
      volumes:
        - name: github-statuses-updater
          secret:
            secretName: github-statuses-updater
        - name: config
          configMap:
            name: tekton-watcher-config
