apiVersion: v1
kind: Namespace
metadata:
  name: tekton-watcher
---
###
# The config map below can be used to customize tekton-watcher.
# Remove the comments and apply it on the cluster.
###
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: tekton-watcher-config
#  namespace: tekton-watcher
#data:
#  config.edn: |
#    {:tekton/namespace "my-namespace"}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-watcher
  namespace: tekton-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-watcher-role
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - pipelineresources
  - pipelineruns
  - tasks
  - taskruns
  verbs:
  - get
  - list
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-watcher-role-binding
subjects:
  - kind: ServiceAccount
    name: tekton-watcher
    namespace: tekton-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-watcher-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-watcher
  namespace: tekton-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-watcher
  template:
    metadata:
     labels:
       app: tekton-watcher
    spec:
      serviceAccountName: tekton-watcher
      containers:
        - name: tekton-watcher
          image: alangh/tekton-watcher:0.1.9
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
            - name: github-statuses-updater
              mountPath: "/etc/github-statuses-updater"
              readOnly: true
            - name: config
              mountPath: "/etc/tekton-watcher"
              readOnly: true
      volumes:
        - name: github-statuses-updater
          secret:
            secretName: github-statuses-updater
        - name: config
          configMap:
            name: tekton-watcher-config
