apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-watcher-role
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - pipelineresources
  - pipelineruns
  - tasks
  - taskruns
  verbs:
  - get
  - list
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  verbs:
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-watcher-role-binding
subjects:
  - kind: ServiceAccount
    name: tekton-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-watcher-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-watcher
  template:
    metadata:
     labels:
       app: tekton-watcher
    spec:
      serviceAccountName: tekton-watcher
      containers:
        - name: tekton-watcher
          image: alangh/tekton-watcher
          volumeMounts:
            - name: github-statuses-updater
              mountPath: "/etc/github-statuses-updater"
              readOnly: true
            - name: config
              mountPath: "/etc/tekton-watcher"
              readOnly: true
      volumes:
        - name: github-statuses-updater
          secret:
            secretName: github-statuses-updater
        - name: config
          configMap:
            name: tekton-watcher-config
